project:
  type: website
  output-dir: docs

website:
  title: "Rafael Campos-Gottardo"
  navbar:
    tools:
        - icon: twitter
          href: https://x.com/rafaelgottardo
        - icon: github
          href: https://github.com/RafaelGottardo
    right:
      - href: index.qmd
        text: Home
      - research.qmd
      - conferences.qmd

format:
  html:
    theme: minty
    css: styles.css 
    toc: false

editor: visual

