---
title: "Conferences"
---

### Papers

Campos-Gottardo, R. (2024, January). Correlates of Populist Attitudes in Canada: Evidence from the CES. Paper presented at the **Bell Chair Graduate Student Conference**, Ottawa, CA. 

[Paper](files/presentations/confpapers/bellchair2024.pdf){.btn .btn-outline-primary .btn role="button"} [Slides](files/presentations/slides/bellchair2024.html){.btn .btn-outline-primary .btn role="button"}
[Code](https://github.com/Rafael-Campos-Gottardo/Correlates-of-Populist-attitudes-in-canada){.btn .btn-outline-primary .btn role="button"}

Campos-Gottardo, R. (2022, August). Populism and authoritarianism during the COVID-19 pandemic: The case of Nayib Bukele in El Salvador. Paper presented at the annual **Congress of the Canadian Association for Latin American and Caribbean Studies**, Toronto, CA.

[Slides](files/presentations/slides/calacs2022.pdf){.btn .btn-outline-primary .btn role="button"} 

### Posters

Campos-Gottardo, R. & Perrella, A. (2023, May). The Role of Populist Attitudes on Support for Centrist Populist Candidates: Evidence From El Salvador. Poster presented at the **Canadian Political Science Association’s Annual Conference**, Toronto, CA.


[Poster](files/presentations/posters/cpsa2023.pdf){.btn .btn-outline-primary .btn role="button"} [Code](link){.btn .btn-outline-primary .btn role="button"}


Campos-Gottardo, R., Jasemi, A., & Gottardo, A. (2022, June). Parenting beliefs about the importance of politics and child qualities: Similarities and differences across borders. Poster presented at **Development 2022**, Calgary, CA. 